require("__spoilage-solution-and-more__.prototypes.tweaks.frozen-eggs-updates")
require("__spoilage-solution-and-more__.prototypes.tweaks.frozen-spoilage-updates")
require("__spoilage-solution-and-more__.prototypes.tweaks.hidden-updates")
require("__spoilage-solution-and-more__.prototypes.tweaks.import-location-updates")
require("__spoilage-solution-and-more__.prototypes.tweaks.reorganization-updates")
